version: "2.4"
services:
  dns:
    image: coredns/coredns:latest
    container_name: dns
    volumes:
      - ./Corefile:/Corefile
      - ./xw.local.hosts:/xw.local.hosts
    networks:
      appnet:
        ipv4_address: 172.18.1.2

  app1:
    image: ng:latest
    container_name: app1
    dns: 172.18.1.2
    volumes:
      - ./app1.conf:/etc/nginx/nginx.conf
      - ./app1.html:/usr/share/nginx/html/index.html
    networks:
      appnet:
        ipv4_address: 172.18.1.11

  app2:
    image: ng:latest
    container_name: app2
    dns: 172.18.1.2
    volumes:
      - ./app2.conf:/etc/nginx/nginx.conf
      - ./app2.html:/usr/share/nginx/html/index.html
    networks:
      appnet:
        ipv4_address: 172.18.1.12

  lb:
    image: ng:latest
    container_name: lb
    dns:
      - 172.18.1.2
    volumes:
      - ./slb1.conf:/etc/nginx/nginx.conf
    networks:
      appnet:
        ipv4_address: 172.18.1.3

networks:
  appnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1


