version: '2.3'
services:
  app1:
    image: openresty/openresty:alpine
    volumes:
      - ./app1.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
  app2:
    image: openresty/openresty:alpine
    volumes:
      - ./app2.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
  ha:
     image: haproxy:alpine
     volumes:
       - ./ha.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
     network_mode: host
